# Generated by Django 3.2.8 on 2021-10-31 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Humanoid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('bio', models.TextField(max_length=2500)),
                ('city', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobile', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('zip_code', models.IntegerField(default=0)),
                ('img_url', models.URLField()),
                ('thumbnail_url', models.URLField()),
            ],
        ),
    ]
